//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportingGodds.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fitness
    {
        public int FitnessId { get; set; }
        public int IdArticles { get; set; }
        public int IdName { get; set; }
        public decimal Price { get; set; }
        public int MaxSale { get; set; }
        public int IdManufacturer { get; set; }
        public int IdSupplier { get; set; }
        public int IdCategory { get; set; }
        public int Sale { get; set; }
        public int Count { get; set; }
        public string FitnessName { get; set; }
        public string PhotoName { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Name Name { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
