//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportingGodds.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickPoint
    {
        public int PickPointId { get; set; }
        public int IdIndex { get; set; }
        public int IdCity { get; set; }
        public int IdStreet { get; set; }
        public int IdHome { get; set; }
    
        public virtual City City { get; set; }
        public virtual Index Index { get; set; }
        public virtual Street Street { get; set; }
    }
}
